# install with  conda env create --prefix ./env --file environment.yaml 
name: dedupe-training-example
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - ipykernel
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pip
  - pytest
  - python ==3.9
  - scipy
  - sqlite
  - pip:
    - dedupe==2.0.11
